# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        release: '21'
    - name: Check java version
      run: java -version
    - name: Analyze Gradle dependencies
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dependencies
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-report
        path: ./**/build/reports/
